[[redirects]]
  from = "/login/*"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/home/*"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
